function [SubSystems_Energy_Table, SubSystems_Performance_Table]=SubSystems_EnergyRate_Fn(Energy_w_rate_in_fan,Energy_w_rate_in_heatingwhole,...
    Energy_w_rate_in_hospital, Energy_w_rate_out_fan, Energy_w_rate_out_heatingwhole,Energy_w_rate_out_hospital,...
    Energy_q_rate_in_fan, Energy_q_rate_in_heatingwhole, Energy_q_rate_in_hospital,...
    Energy_q_rate_out_fan, Energy_q_rate_out_heatingwhole, Energy_q_rate_out_hospital,...
    Energy_q_rate_loss_fan, Energy_q_rate_loss_heatingwhole, Energy_q_rate_loss_hospital,...
    ...
    Energy_rate_in_fan, Energy_rate_in_heatingwhole,Energy_rate_in_hospital,...
    Energy_utilized_rate_fan, Energy_utilized_rate_heatingwhole,Energy_utilized_rate_hospital,...
    ...
    Exg_rate_in_fan, Exg_rate_in_heatingwhole,Exg_rate_in_hospital,...
    Exg_utilized_rate_fan, Exg_utilized_rate_heatingwhole,Exg_utilized_rate_hospital,...
    Exg_q_rate_loss_fan, Exg_q_rate_loss_heatingwhole, Exg_q_rate_loss_hospital,...
    ...
    sigma_dot_p_fan, sigma_dot_p_heatingwhole, sigma_dot_p_hospital, Exg_d_rate_fan, Exg_d_rate_heatingwhole, Exg_d_rate_hospital,...
    eff_energy_fan, eff_energy_heatingwhole, eff_energy_hospital,eff_exergy_fan, eff_exergy_heatingwhole, eff_exergy_hospital)

        %% Table: Energy Flows Related to Components
        SubSystems_Label = {'Fan'; 'The Whole Heating System by Furnace'; 'Hospital Air Distribution'};
        Power_In_SubSystems = [Energy_w_rate_in_fan; Energy_w_rate_in_heatingwhole; Energy_w_rate_in_hospital];
        Power_Out_SubSystems = [Energy_w_rate_out_fan; Energy_w_rate_out_heatingwhole; Energy_w_rate_out_hospital];
        Heat_In_SubSystems = [Energy_q_rate_in_fan; Energy_q_rate_in_heatingwhole; Energy_q_rate_in_hospital];
        Heat_Out_SubSystems = [Energy_q_rate_out_fan; Energy_q_rate_out_heatingwhole; Energy_q_rate_out_hospital]; % - Q_dot_ for heating will change
        Heat_Loss_SubSystems = [Energy_q_rate_loss_fan; Energy_q_rate_loss_heatingwhole; Energy_q_rate_loss_hospital]; % - Q_dot_ for heating will change
        
        SubSystems_Energy_Table = table(SubSystems_Label, Power_In_SubSystems, Power_Out_SubSystems, Heat_In_SubSystems, Heat_Out_SubSystems,Heat_Loss_SubSystems,...
            'VariableNames', {'Subsystem (Components)','Power In [W]', 'Power Out [W]','Heat In [W]','Heat Out [W]','Heat Loss [W]'});
        
        disp('Table 2: Energy [Rate] Related to Components (Sub-systems)');
        disp(SubSystems_Energy_Table);
        
        %% Table: Performance Related to Components
        %SubSystems_Label = {'Fan'; 'The Whole Heating System by Furnace'; 'Hospital Air Distribution'};
        sigma_dot_p = [sigma_dot_p_fan; sigma_dot_p_heatingwhole; sigma_dot_p_hospital];
        Exg_d_rate = [Exg_d_rate_fan; Exg_d_rate_heatingwhole; Exg_d_rate_hospital];

        Energy_in = [Energy_rate_in_fan; Energy_rate_in_heatingwhole; Energy_rate_in_hospital];
        Energy_utilized_rate = [Energy_utilized_rate_fan; Energy_utilized_rate_heatingwhole;Energy_utilized_rate_hospital];
        Energy_loss_rate = Heat_Loss_SubSystems;

        Exg_in_rate = [Exg_rate_in_fan; Exg_rate_in_heatingwhole;Exg_rate_in_hospital];
        Exg_utilized = [Exg_utilized_rate_fan; Exg_utilized_rate_heatingwhole;Exg_utilized_rate_hospital];
        Exg_loss_rate = [Exg_q_rate_loss_fan; Exg_q_rate_loss_heatingwhole;Exg_q_rate_loss_hospital];
        
        Energy_utilization_percent = [eff_energy_fan * 100; eff_energy_heatingwhole * 100; eff_energy_hospital*100];
        Exg_utilization_percent = [eff_exergy_fan * 100; eff_exergy_heatingwhole * 100; eff_exergy_hospital*100];
        
        SubSystems_Performance_Table = table(SubSystems_Label, sigma_dot_p, Exg_d_rate, ...
            Energy_in, Energy_utilized_rate, Energy_loss_rate,Exg_in_rate, Exg_utilized,Exg_loss_rate, ...
            Energy_utilization_percent, Exg_utilization_percent,...
            'VariableNames', {'Subsystem (Components)','Entropy Production Rate [W/K]','Exergy Destruction Rate [W]',...
            'Energy Input Rate [W]','Energy Utilized Rate [W]', 'Energy Loss Rate [W]',...
            'Exergy Input Rate [W]','Exergy Utilized Rate [W]','Exergy Loss Rate [W]',...
            'Energy Utilization Efficiency [%]','Exergetic Efficiency [%]'});
        
        disp('Table 3: Performance [Rate] Related to Components (Sub-systems)');
        disp(SubSystems_Performance_Table);

end